name: ci

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade poetry
        poetry install --extras archive
    - run: poetry run pytest --cov=ampel --integration
      env:
        ARCHIVE_TOPIC_TOKEN: ${{ secrets.ARCHIVE_TOPIC_TOKEN }}
        ARCHIVE_TOKEN: ${{ secrets.ARCHIVE_TOKEN }}
  
  mypy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade poetry
        poetry install --extras archive
    - run: poetry run mypy --namespace-packages -p ampel
